name: Deploy
description: "Deploy Action"

inputs:
  github_token:
    description: "github_token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: 'npm'

    - run: |
        rm -rf out
        corepack enable npm
        npm ci
        npm run build
        npx next export
        touch out/.nojekyll
      shell: bash
      env:
        PREFIX: /world-statistics-on-poop

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: out
