name: Collect

on:
  schedule:
  - cron: '15 12 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: 'npm'

    - run: |
        corepack enable npm
        npm ci
        npm run collect
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Git commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data/
        git commit -m 'Update results.'
        git push

    - name: Trigger deploy workflow.
      run: gh workflow run deploy.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
