name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: "16"

    - run: |
        rm -rf out
        npm ci
        npm run build
        npx next export
        touch out/.nojekyll
      env:
        PREFIX: /world-statistics-on-poop

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out
